# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tutorials for SBME Students 
author: Asem Alaa
email: asem.a.abdelaziz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  These pages contain online teaching materials prepared by teaching assistants
  in the biomedical engineering department at Cairo University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  A-Alaa

# Google Analytics
google_analytics: UA-136835686-1

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

theme: minima

plugins:
  - jekyll-feed
  - jemoji
  # sudo apt-get install build-essential patch ruby-dev zlib1g-dev
  # - jekyll-pdf


# scholar:
#   style: mla


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitmodules/
  - .git-rewrite/
  - .github/
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .ipynb_checkpoints
  
sass:
  load_paths:
    - css
    - nbconvert